# Generated by Django 3.0.7 on 2020-06-12 14:28

import chatterbot.conversation
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_chatterbot', '0018_text_max_length'),
        ('bot', '0003_auto_20200421_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time that the statement was created at.')),
                ('persona', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=65535)),
                ('search_text', models.CharField(blank=True, max_length=65535)),
                ('in_response_to', models.CharField(max_length=65535, null=True)),
                ('search_in_response_to', models.CharField(blank=True, max_length=65535)),
                ('tags', models.ManyToManyField(related_name='bot_statements', to='django_chatterbot.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, chatterbot.conversation.StatementMixin),
        ),
    ]
