# Generated by Django 3.0.7 on 2020-06-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='statement',
            name='tags',
            field=models.ManyToManyField(related_name='bot_statements', to='bot.Tag'),
        ),
    ]
