# Generated by Django 3.0.7 on 2020-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20200615_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asked',
            field=models.BigIntegerField(default=1, verbose_name='nombre de fois que la question a été posée'),
        ),
    ]