# Generated by Django 3.0.7 on 2020-06-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
