maazertyuioazertyuiazerftgyhuxsdcfvgbhnjkcnzhiczhhuzheicuhuichuiczhcuiechuizcnzeifczeciuhcuiimaazertyuioazertyuiazerftgyhuxsdcfvgbhnjkcnzhiczhhuzheicuhuichuiczhcuiechuizcnzeifczeciuhcuii = (
    3
)
print(
    maazertyuioazertyuiazerftgyhuxsdcfvgbhnjkcnzhiczhhuzheicuhuichuiczhcuiechuizcnzeifczeciuhcuiimaazertyuioazertyuiazerftgyhuxsdcfvgbhnjkcnzhiczhhuzheicuhuichuiczhcuiechuizcnzeifczeciuhcuii
)
