version: "3"
services:
  cache:
    image: redis:alpine
    container_name: redis-memoire
    expose:
      - "6379"
    entrypoint: redis-server
    networks:
      memoire-dev:
        aliases:
          - redis
  celery:
    build:
      context: ..
      dockerfile: Docker/Dockerfiles/Django
    command: celery -A memoire worker -l info
    volumes:
      - ../backend/:/api
    depends_on:
      - db
      - cache
    links:
      - db:database
      - cache:redis
    env_file:
      - env/base/api.env
      - env/base/db.env
      - env/dev/api.env
      - env/dev/db.env
    networks:
      memoire-dev:
        aliases:
          - celery
  db:
    image: postgres:alpine
    container_name: postgres-memoire
    ports:
      - "5433:5432"
    env_file:
      - env/base/db.env
      - env/dev/db.env
    volumes:
      - ./postgres-data-memoire-dev:/var/lib/postgresql/data
    networks:
      memoire-dev:
        aliases:
          - database
  api:
    container_name: api-memoire
    build:
      context: ..
      dockerfile: Docker/Dockerfiles/Django
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
      - sandbox
    links:
      - db:database
      - cache:redis
      - sandbox:codejail
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             uvicorn --host 0.0.0.0 --port 8080 memoire.asgi:application --reload"
    volumes:
      - ../backend/:/api
    env_file:
      - env/base/api.env
      - env/base/db.env
      - env/dev/api.env
      - env/dev/db.env
    networks:
      memoire-dev:
        aliases:
          - api
  sandbox:
    container_name: sandbox-memoire
    build:
      context: ..
      dockerfile: Docker/Dockerfiles/Sandbox
    ports:
    - "8081:8081"
    security_opt:
      - apparmor:/sandbox-virtualenv/bin/python
    command: >
     sh -c "pipenv shell &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py collectstatic --noinput &&
            uvicorn --host 0.0.0.0 --port 8080 code_sandbox.asgi:application --reload"
    volumes:
      - ../code_sandbox/:/api
    env_file:
      - env/base/api.env
      - env/base/db.env
      - env/dev/api.env
      - env/dev/db.env
    networks:
      memoire-dev:
        aliases:
          - codejail
  vue:
    container_name: vue-memoire-serve
    build:
      context: ..
      dockerfile: Docker/Dockerfiles/Vue-Serve
    volumes:
      - ../frontend/memoire-app:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      memoire-dev:
        aliases:
          - vue
networks:
  memoire-dev:
    driver: bridge