version: "3"
services:
  cache:
    image: redis:alpine
    container_name: redis-memoire
    expose:
      - "6379"
    entrypoint: redis-server
    networks:
      memoire-prod:
        aliases:
          - redis
  celery:
    build:
      context: ..
      dockerfile: Docker/Dockerfiles/Django
    command: celery -A memoire worker -l info
    volumes:
      - ../backend/:/api
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - cache
    links:
      - db:database
      - cache:redis
    env_file:
      - env/base/api.env
      - env/base/db.env
      - env/prod/api.env
      - env/prod/db.env
    networks:
      memoire-prod:
        aliases:
          - celery
  db:
    image: postgres:alpine
    container_name: postgres-memoire
    ports:
      - "5433:5432"
    env_file:
      - env/base/db.env
      - env/prod/db.env
    volumes:
      - ./postgres-data-memoire-prod:/var/lib/postgresql/data
    networks:
      memoire-prod:
        aliases:
          - database
  api:
    container_name: api-memoire
    build:
      context: ..
      dockerfile: Docker/Dockerfiles/Django
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    links:
      - db:database
      - cache:redis
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -e ssl:8080:privateKey=./ssl/privekey.pem:certKey=./ssl/cert.pem -b 0.0.0.0 -p 8000 memoire.asgi:application"
    volumes:
      - ../backend/:/api
      - ../backend/bot/files/:/usr/local/lib/python3.8/site-packages/chatterbot_corpus/data/french/
      - /var/run/docker.sock:/var/run/docker.sock
      - ../web/ssl:/api/ssl
    env_file:
      - env/base/api.env
      - env/base/db.env
      - env/prod/api.env
      - env/prod/db.env
    networks:
      memoire-prod:
        aliases:
          - api
networks:
  memoire-prod:
    driver: bridge
