# Generated by Django 3.1 on 2020-08-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=60)),
                ('image_name', models.CharField(max_length=60)),
                ('image_id', models.CharField(blank=True, max_length=60, null=True)),
                ('dockerfile', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
