# Generated by Django 3.0.4 on 2020-03-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sandbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sandboxprofile", name="image_id", field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
