# Generated by Django 3.0.4 on 2020-03-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandboxprofile',
            name='profile_name',
            field=models.CharField(max_length=60),
        ),
    ]
