# Generated by Django 3.0.3 on 2020-02-29 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.Tag', verbose_name='Tags associés'),
        ),
        migrations.AlterField(
            model_name='session',
            name='in_charge_persons',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Les personnes responsables'),
        ),
    ]
