# Generated by Django 3.0.5 on 2020-04-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='dockerImage',
            new_name='docker_image',
        ),
    ]
