# Generated by Django 3.0.3 on 2020-02-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code_output',
            field=models.TextField(),
        ),
    ]
