# Generated by Django 3.0.3 on 2020-02-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'catégorie'},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name': 'difficulté'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'exercice'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'TP'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'soumission'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag'},
        ),
        migrations.AlterModelOptions(
            name='targetstudents',
            options={'verbose_name': 'étudiant cible', 'verbose_name_plural': 'étudiants cibles'},
        ),
    ]
