# Generated by Django 3.0.3 on 2020-03-02 15:01

from django.db import migrations, models
import django.utils.timezone
import exercises.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20200229_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Moment de la soumission'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='project_files',
            field=models.FileField(blank=True, null=True, upload_to=exercises.models.utils.path_and_rename),
        ),
    ]
