# Generated by Django 3.0.5 on 2020-04-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_errorsexercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name="code de l'erreur")),
            ],
        ),
        migrations.AlterField(
            model_name='errorsexercise',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercises.Error'),
        ),
    ]
