# Generated by Django 3.0.3 on 2020-02-24 23:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20200224_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code_output',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
