# Generated by Django 3.0.4 on 2020-03-05 13:18

from django.db import migrations, models
import django.db.models.deletion
import exercises.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sandbox', '0001_initial'),
        ('exercises', '0003_auto_20200302_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom de la dépendance')),
            ],
            options={
                'verbose_name': 'requirement',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='dockerImage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sandbox.SandboxProfile', verbose_name='Image docker associée'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='project_files',
            field=models.FileField(default='', upload_to=exercises.models.utils.path_and_rename, validators=[exercises.models.utils.validate_file_extensions]),
        ),
        migrations.AddField(
            model_name='exercise',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.Requirement', verbose_name='Dépendances associées'),
        ),
    ]
