# Generated by Django 3.0.3 on 2020-02-25 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0004_auto_20200224_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'catégorie'},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={'verbose_name': 'difficulté'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'exercice'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'section'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'TP'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'verbose_name': 'soumission'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag'},
        ),
        migrations.AlterModelOptions(
            name='targetstudents',
            options={'verbose_name': 'étudiant cible', 'verbose_name_plural': 'étudiants cibles'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, to='exercises.Tag', verbose_name='Tags associés'),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exercises.Section'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Date de la séance'),
        ),
        migrations.AlterField(
            model_name='session',
            name='in_charge_persons',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Les personnes responsables'),
        ),
        migrations.AlterField(
            model_name='session',
            name='target',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='exercises.TargetStudents', verbose_name="Séance à destination de ce type d'étudiants"),
        ),
    ]
