# Generated by Django 3.0.5 on 2020-04-16 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0004_auto_20200415_1413'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ErrorsExercise',
            new_name='ErrorExercise',
        ),
    ]
