# Generated by Django 3.0.4 on 2020-03-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20200305_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='exercises_requirements', to='exercises.Requirement', verbose_name='Dépendances associées'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exercises_tags', to='exercises.Tag', verbose_name='Tags associés'),
        ),
    ]
