# Generated by Django 3.0.5 on 2020-04-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20200416_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name': 'erreur'},
        ),
        migrations.AlterModelOptions(
            name='errorexercise',
            options={'verbose_name': 'erreur exercice'},
        ),
    ]
