# Generated by Django 3.0.4 on 2020-03-07 12:04

import constrainedfilefield.fields.file
from django.db import migrations
import exercises.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20200306_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='project_files',
            field=constrainedfilefield.fields.file.ConstrainedFileField(content_types=['application/gzip'], default='', mime_lookup_length=4096, storage=exercises.models.utils.OverwriteStorage(), upload_to=exercises.models.utils.path_and_rename, validators=[exercises.models.utils.validate_file_extensions]),
        ),
    ]
