# Generated by Django 3.0.3 on 2020-02-27 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0006_auto_20200227_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='in_charge_persons',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Les personnes responsables'),
        ),
        migrations.AlterField(
            model_name='session',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exercises.TargetStudents', verbose_name="Séance à destination de ce type d'étudiants"),
        ),
    ]
