# Generated by Django 3.0.5 on 2020-04-17 11:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0008_auto_20200417_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ErrorExercise',
            new_name='ErrorsExercise',
        ),
        migrations.AlterModelOptions(
            name='errorsexercise',
            options={'verbose_name': 'erreurs exercice'},
        ),
    ]
