# Generated by Django 3.0.5 on 2020-04-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_auto_20200417_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='exercises_errors', to='exercises.ErrorCount', verbose_name='Erreurs détectées'),
        ),
        migrations.DeleteModel(
            name='ErrorsExercise',
        ),
    ]
