# Generated by Django 3.0.5 on 2020-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_auto_20200417_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='final',
            field=models.BooleanField(default=False, verbose_name='Type de la soumission est finale'),
        ),
    ]
