# Generated by Django 3.0.5 on 2020-04-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20200417_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='message',
            field=models.CharField(default='', max_length=1000, verbose_name="message de l'erreur"),
        ),
        migrations.AddField(
            model_name='error',
            name='type_error',
            field=models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('advice', 'Advice')], default='error', max_length=32, verbose_name="type d'erreur"),
        ),
    ]
