# Generated by Django 3.0.5 on 2020-04-22 07:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_auto_20200421_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code_input',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
