# Generated by Django 3.0.5 on 2020-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0013_auto_20200422_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='code_input',
            field=models.TextField(),
        ),
    ]
