# Generated by Django 3.0.7 on 2020-06-13 07:34

import constrainedfilefield.fields.file
from django.db import migrations
import exercises.models.storage_utils


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0015_auto_20200422_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='project_files',
            field=constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=['application/gzip'], default='', mime_lookup_length=4096, storage=exercises.models.storage_utils.OverwriteStorage(), upload_to=exercises.models.storage_utils.path_and_rename, validators=[exercises.models.storage_utils.validate_file_extensions]),
        ),
    ]
