# Generated by Django 3.0.7 on 2020-06-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_auto_20200613_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom du template')),
                ('errors', models.ManyToManyField(blank=True, related_name='errorTemplate_errors', to='exercises.Error', verbose_name='Erreurs associées')),
            ],
            options={
                'verbose_name': "templates d'erreurs",
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='errors_template',
            field=models.ManyToManyField(blank=True, related_name='exercises_errorsTemplate', to='exercises.ErrorTemplate', verbose_name="Templates d'erreurs associés"),
        ),
    ]
