# Generated by Django 3.0.7 on 2020-06-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_auto_20200613_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorstemplate',
            options={'verbose_name': "template d'erreurs", 'verbose_name_plural': "templates d'erreurs"},
        ),
    ]
