# Generated by Django 3.0.7 on 2020-06-15 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_auto_20200613_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.Session', verbose_name="Session de l'exercice"),
        ),
    ]
